### ISSUE TITLE
predict和test方法为啥返回值类型是str、float

### ISSUE THREAD

**Issue by fatherfox** [2shou/TextGrocery#10]
Traceback (most recent call last):
  File "/home/fatherfox/PycharmProjects/grocery/test.py", line 28, in <module>
    print grocery.predict('考生必读：新托福写作考试评分标准').dec_values
AttributeError: 'str' object has no attribute 'dec_values'

**Comment by 2shou** [comment]
了解下你安装的是最新的代码版本么？
另外你的Python版本是？

**Comment by fatherfox** [comment]
用pip直接装的。。。
python用的cent自带的2.6.6。。。

**Comment by 2shou** [comment]
建议升级到2.7再试试。

**Comment by fatherfox** [comment]
python 2.7.10还是同样问题~~~~

**Comment by 2shou** [comment]
麻烦把你的完整代码贴一下。

**Comment by grapeot** [comment]
我也遇到了同样的问题，也是从pip install装的。经过从git clone, install后问题解决。我猜测可能是pip上的版本和git上的不一样。

**Comment by 2shou** [comment]
@grapeot 
多谢提醒！pip版本已更新。
