### ISSUE TITLE
请教一下运行环境问题

### ISSUE THREAD

**Issue by ulyancc** [2shou/TextGrocery#11]
请教一下，在MAC osx，python2.7环境下，试运行

from tgrocery import Grocery

会出现错误：OSError: dlopen(/Users/user/Library/Python/2.7/lib/python/site-packages/tgrocery/learner/util.so.1, 6): image not found

请问是什么原因，谢谢！

**Comment by 2shou** [comment]
感觉像环境冲突的问题。你可以下载源码之后make，然后把本地路径下的util.so.1拷贝到对应目录。
