### ISSUE TITLE
请问用了jieba分词， 怎样导入自定义词典

### ISSUE THREAD

**Issue by lgh0504** [2shou/TextGrocery#23]
请问用了jieba分词， 怎样导入自定义词典
我自己用jieba分词可以导入自定义的词典， 在TextGorcery里，这么弄可以吗？

**Comment by 2shou** [comment]
在[converter.py的33行](https://github.com/2shou/TextGrocery/blob/afcc66b23b13b9ec9d6e3c9b84d45830688afdd0/tgrocery/converter.py#L33)改就好
