### ISSUE TITLE
重新load模型之后，不能用自定义的分词来predict~

### ISSUE THREAD

**Issue by tanghuiyu** [2shou/TextGrocery#6]

**Comment by tanghuiyu** [comment]
使用了TextGrocery之后文本分类准确率得到很大提升~非常感谢~
ps：
能不能开放输出概率矩阵的接口呢？就是在输出预测结果的时候能够输出n个结果以及其对应的概率~

**Comment by 2shou** [comment]
实际上已经实现了。
TextGrocery的预测结果是一个`GroceryPredictResult`对象，它的`dec_values`属性代表了结果从属于不同类别的**决策变量**（值越大，属于该类别的概率越高）。不过，取值并不是严格符合`[0,1]`区间分布的，会有负数，你可以通过一些公式自行转换。
