### ISSUE TITLE
多分类的训练语料数目的比例如何确定

### ISSUE THREAD

**Issue by CasyWang** [2shou/TextGrocery#7]
比如我现在有3个分类 C1, C2, C3, 这三个分类的语料的比例要保持1：1：1吗？

**Comment by 2shou** [comment]
是的，SVM是一个对样本均衡性要求很高的算法。

**Comment by CasyWang** [comment]
如果是多分类，假设总共有5个分类，但是我现在只能总结并找出3个分类进行训练，用该模型做分类时，如果碰到剩余2个类别的文本，能不能输出 类似E_TOPIC_UNKNOWN（分类不详）？

**Comment by 2shou** [comment]
这是不行的，SVM是一种监督学习方法，必须要有标签数据。
你的问题可考虑两种思路：

1. 采集一些未知类别的样本，标注为`分类不详`，放入模型一起训练
2. 辅助用半监督或者聚类的方法，比如这哥们介绍的[直推式SVM](https://charlesmartin14.wordpress.com/2014/09/23/machine-learning-with-missing-labels-transductive-svms/)，可以在仅有正样本的情况下工作，也就是先利用已有标签的样本构造一个顶层分类器，作用是区分`可分类`和`不可分类`，对于`可分类`的样本再用普通SVM分

第二种方法之前尝试过，效果并不是很理想，探索为主，哈。

**Comment by CasyWang** [comment]
能否给我你的Email？ 我扒取了应用市场的几万条评论，分了几个主题，你帮我看看这样的测试样本标注是否正确(类别主题之间是否存在重叠)？Thanks, 2shou.

**Comment by 2shou** [comment]
博客里有写邮件地址。

在 2015年9月6日 下午4:16，oliverwang <notifications@github.com>写道：

**Comment by rollingdeep** [comment]
如果我的多分类语料不均衡，如果将多个分类的语料均衡合并到1:1:1,应该可行吧。
