### ISSUE TITLE
python3不友好……ImportError: No module named 'converter'

### ISSUE THREAD

**Issue by ClericPy** [2shou/TextGrocery#8]
不知道有没有python3版本下的推荐……

**Comment by 1354092549** [comment]
我也遇到了这个问题

**Comment by JingkaiTang** [comment]
作者已经弃坑了吧，看到有人做了2to3的移植不知道能用不？
[链接](https://github.com/PrashntS/TextGrocery/commit/af2817c384a4255a09e15a955e8274f63fe09586)

**Comment by 2shou** [comment]
最近确实没有时间维护这个项目了，欢迎大家提交PR给我。

**Comment by gramster** [comment]
Is this a Python 3 issue?

**Comment by 1354092549** [comment]
@gramster Yes, it seems not to work on Python 3

**Comment by 2shou** [comment]
@gramster Don't use it under Python 3.
